### ISSUE TITLE
Can't build for iOS 

### ISSUE THREAD

**Issue by shaiful73** [mpvkit/gnutls-build#2]
1 error generated.
make[4]: 
*** [dlwrap/zstd.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
In file included from /Users/shaiful/Developer/IOSGNUTLS/gnutls-build/dist/gnutls-3.8.7/lib/dlwrap/brotlienc.c:12:
/Users/shaiful/Developer/IOSGNUTLS/gnutls-build/dist/gnutls-3.8.7/lib/dlwrap/brotlienc.h:11:10: fatal error: 
'brotli/encode.h' file not found
   11 | #include <brotli/encode.h>
      |          ^~~~~~~~~~~~~~~~~
1 error generated.
make[4]: *** [dlwrap/brotlienc.lo] Error 1
In file included from /Users/shaiful/Developer/IOSGNUTLS/gnutls-build/dist/gnutls-3.8.7/lib/dlwrap/brotlidec.c:12:
/Users/shaiful/Developer/IOSGNUTLS/gnutls-build/dist/gnutls-3.8.7/lib/dlwrap/brotlidec.h:11:10: fatal error: 
'brotli/decode.h' file not found
   11 | #include <brotli/decode.h>
      |          ^~~~~~~~~~~~~~~~~
1 error generated.
make[4]: *** [dlwrap/brotlidec.lo] Error 1
make[3]: 
*** [all-recursive] Error 1
make[2]: 
*** [all] Error 2
make[1]: 
*** [all-recursive] Error 1
make: *** [all] Error 2
please view log file for detail: file:///Users/shaiful/Developer/IOSGNUTLS/gnutls-build/dist/gnutls/ios/scratch/arm64.log

The operation couldn’t be completed. (make execute failed error 2.)
make: *** [build] Error 1
17:58:36 ~/Developer/IOSGNUTLS/gnutls-build $ make build platform=ios

**Comment by cxfksword** [comment]
3.8.7 is not yet compatible, you can use 3.8.6 first.

**Comment by cxfksword** [comment]
I've updated to version 3.8.8, which is compatible but requires macOS 15 or later.

**Comment by shaiful73** [comment]
It's working version 3.8.8. Thank you.
